<?php

namespace Tests\Feature;

use App\Models\Attendance;
use App\Models\CertificateTemplate;
use App\Models\ParticipationType;
use App\Models\Permission;
use App\Models\Role;
use App\Models\Setting;
use App\Models\User;
use App\Models\Workshop;
use App\Services\CertificateRenderer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class RegistroModuleTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        $user = User::factory()->create();
        $role = Role::firstOrCreate(['name' => 'Administrator']);
        $user->roles()->sync([$role->id]);

        return $user;
    }

    private function userWith(string $roleName, array $permissionKeys, array $attributes = []): User
    {
        $role = Role::firstOrCreate(['name' => $roleName]);

        foreach ($permissionKeys as $key) {
            $role->permissions()->syncWithoutDetaching(
                Permission::firstOrCreate(['key' => $key], [
                    'module' => 'Test',
                    'label' => $key,
                ])
            );
        }

        $user = User::factory()->create($attributes);
        $user->roles()->sync([$role->id]);

        return $user;
    }

    private function eventoType(): ParticipationType
    {
        return ParticipationType::create([
            'key' => 'evento_asistencia',
            'label' => 'Asistente al evento',
            'event_kind' => 'event',
            'role' => null,
            'is_active' => true,
        ]);
    }

    private function enableEventCheckin(): void
    {
        Setting::create(['key' => 'evento_checkin_enabled', 'value' => '1']);
        Setting::create(['key' => 'evento_nombre', 'value' => 'EICAL 2026']);
        Setting::create(['key' => 'evento_min_dias', 'value' => '1']);
    }

    private function badgeTemplate(bool $autoFit = false): CertificateTemplate
    {
        $template = CertificateTemplate::create([
            'name' => 'Gafete base',
            'kind' => 'badge',
            'is_default' => true,
            'width' => 1000,
            'height' => 1500,
        ]);

        $template->elements()->create([
            'type' => 'text',
            'content' => '{nombre}',
            'x' => 100,
            'y' => 100,
            'width' => 800,
            'height' => 60,
            'font_size' => 40,
            'font_weight' => 'bold',
            'auto_fit' => $autoFit,
            'text_align' => 'center',
            'z_index' => 1,
        ]);

        return $template;
    }

    private function badgeFontSize(): float
    {
        $content = $this->get('/gafete/imprimir')->getContent();

        preg_match('/font-size:([\d.]+)px/', $content, $matches);
        $this->assertNotEmpty($matches, 'No se encontró font-size en el gafete');

        return (float) $matches[1];
    }

    public function test_checkin_token_is_autogenerated_when_user_is_created()
    {
        $user = User::factory()->create();

        $this->assertNotNull($user->checkin_token);
        $this->assertStringStartsWith('GFT-', $user->checkin_token);
    }

    public function test_user_can_view_own_gafete()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/gafete')->assertOk();
    }

    public function test_user_without_permission_cannot_view_gafete()
    {
        $user = $this->userWith('Asistente', ['dashboard.view']);
        $this->actingAs($user);

        $this->get('/gafete')->assertForbidden();
    }

    public function test_user_can_print_badge_html()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $response = $this->get('/gafete/imprimir');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
        $this->assertStringContainsString($user->first_name, $response->getContent());
        $this->assertStringContainsString('EICAL 2026', $response->getContent());
        $this->assertStringContainsString('data:image/svg+xml;base64', $response->getContent());
        $this->assertStringContainsString('@page { size: 7.5cm 12.5cm; margin: 0; }', $response->getContent());
        $this->assertStringContainsString('name="viewport"', $response->getContent());
        $this->assertStringContainsString('print-color-adjust: exact', $response->getContent());
    }

    public function test_badge_shows_all_user_roles()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $user->roles()->syncWithoutDetaching([Role::firstOrCreate(['name' => 'Ponente'])->id]);
        $this->actingAs($user);

        $this->get('/gafete')->assertOk();
        $this->assertStringContainsString('Asistente | Ponente', $this->get('/gafete/imprimir')->getContent());
        $this->assertStringContainsString('Asistente | Ponente', $this->get('/gafete')->getContent());
    }

    public function test_user_can_download_badge_pdf()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $response = $this->get('/gafete/imprimir/pdf');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'application/pdf');
        $this->assertStringStartsWith('%PDF', $response->getContent());
    }

    public function test_badge_pdf_prints_on_75x125_mm_paper()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $content = $this->get('/gafete/imprimir/pdf')->getContent();

        preg_match('/MediaBox\s*\[\s*[\d.]+\s+[\d.]+\s+([\d.]+)\s+([\d.]+)\s*\]/', $content, $matches);

        $this->assertNotEmpty($matches, 'No se encontró MediaBox en el PDF del gafete');
        $this->assertEqualsWithDelta(212.6, (float) $matches[1], 0.2);
        $this->assertEqualsWithDelta(354.33, (float) $matches[2], 0.2);
    }

    public function test_badge_print_page_is_responsive_on_screen()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $content = $this->get('/gafete/imprimir')->getContent();

        $this->assertStringContainsString('@media screen', $content);
        $this->assertStringContainsString('100vw', $content);
        $this->assertStringContainsString('fitStage', $content);
        $this->assertStringContainsString('badge-stage', $content);
    }

    public function test_badge_template_is_used_when_available()
    {
        $this->badgeTemplate();
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $content = $this->get('/gafete/imprimir')->getContent();

        $this->assertStringContainsString($user->first_name, $content);
        $this->assertStringNotContainsString('badge-name', $content);
    }

    public function test_auto_fit_shrinks_long_names_in_badge()
    {
        $this->badgeTemplate(autoFit: true);
        $longUser = $this->userWith('Asistente', ['gafete.view'], [
            'first_name' => 'María Fernanda Hernández González',
            'last_name' => 'Rodríguez López',
        ]);
        $this->actingAs($longUser);
        $longSize = $this->badgeFontSize();
        $content = $this->get('/gafete/imprimir')->getContent();
        $this->assertStringContainsString(
            'white-space:nowrap;',
            $content,
        );
        $this->assertStringContainsString('data-auto-fit="1"', $content);
        $this->assertStringContainsString('measureText', $content);
        $this->assertStringContainsString('data-max-font-size="', $content);

        $this->badgeTemplate(autoFit: true);
        $shortUser = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($shortUser);
        $shortSize = $this->badgeFontSize();

        $this->assertLessThan($shortSize, $longSize);
    }

    public function test_auto_fit_never_grows_beyond_configured_font_size()
    {
        $template = $this->badgeTemplate(autoFit: true);
        $shortUser = $this->userWith('Asistente', ['gafete.view'], [
            'first_name' => 'Ana',
            'last_name' => 'Li',
        ]);
        $this->actingAs($shortUser);
        $fitSize = $this->badgeFontSize();

        $template->elements()->update(['auto_fit' => false]);
        $baseSize = $this->badgeFontSize();

        $this->assertEqualsWithDelta($baseSize, $fitSize, 0.01);
    }

    public function test_auto_fit_is_opt_in()
    {
        $this->badgeTemplate(autoFit: false);
        $longUser = $this->userWith('Asistente', ['gafete.view'], [
            'first_name' => 'María Fernanda Hernández González',
            'last_name' => 'Rodríguez López',
        ]);
        $this->actingAs($longUser);
        $longSize = $this->badgeFontSize();
        $content = $this->get('/gafete/imprimir')->getContent();
        $this->assertStringNotContainsString('data-auto-fit="1"', $content);

        $this->badgeTemplate(autoFit: false);
        $shortUser = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($shortUser);
        $shortSize = $this->badgeFontSize();

        $this->assertEqualsWithDelta($shortSize, $longSize, 0.01);
    }

    public function test_scan_info_page_is_public()
    {
        $this->get('/gafete/escaneo?token=GFT-ABC')
            ->assertOk()
            ->assertSee('GFT-ABC');
    }

    public function test_staff_with_permission_can_access_checkin()
    {
        $this->enableEventCheckin();
        $user = $this->userWith('Ponente', ['checkin.scan']);
        $this->actingAs($user);

        $this->get('/checkin')->assertOk();
    }

    public function test_user_without_permission_cannot_access_checkin()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/checkin')->assertForbidden();
    }

    public function test_staff_can_print_participant_badge_html()
    {
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = $this->userWith('Asistente', ['gafete.view'], [
            'first_name' => 'María Fernanda',
            'last_name' => 'Hernández González',
        ]);
        $this->actingAs($staff);

        $response = $this->get("/checkin/gafete/{$participant->id}/imprimir");

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
        $content = $response->getContent();
        $this->assertStringContainsString('María Fernanda Hernández González', $content);
        $this->assertStringContainsString($participant->dni, $content);
    }

    public function test_staff_can_download_participant_badge_pdf()
    {
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($staff);

        $response = $this->get("/checkin/gafete/{$participant->id}/imprimir/pdf");

        $response->assertOk();
        $response->assertHeader('Content-Type', 'application/pdf');
        $this->assertStringStartsWith('%PDF', $response->getContent());
    }

    public function test_non_staff_cannot_print_other_participant_badge()
    {
        $participant = $this->userWith('Asistente', ['gafete.view']);

        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get("/checkin/gafete/{$participant->id}/imprimir")->assertForbidden();
        $this->get("/checkin/gafete/{$participant->id}/imprimir/pdf")->assertForbidden();
    }

    public function test_checkin_registers_attendance_and_issues_event_certificate()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $response = $this->postJson('/checkin/register', ['token' => $participant->checkin_token]);

        $response->assertOk()->assertJson(['success' => true]);
        $this->assertDatabaseHas('attendances', [
            'user_id' => $participant->id,
            'workshop_id' => null,
            'presentation_id' => null,
        ]);
        $this->assertDatabaseHas('certificates', [
            'user_id' => $participant->id,
            'event_type' => 'event',
        ]);
    }

    public function test_checkin_rejects_invalid_token()
    {
        $this->enableEventCheckin();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => 'GFT-INVALIDO'])
            ->assertOk()
            ->assertJson(['success' => false]);
    }

    public function test_staff_can_lookup_users_by_partial_name()
    {
        $this->enableEventCheckin();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create([
            'first_name' => 'María',
            'last_name' => 'García',
        ]);
        $this->actingAs($staff);

        $this->get('/checkin/lookup?search=gar')
            ->assertOk()
            ->assertJsonFragment([
                'id' => $participant->id,
                'checkin_token' => $participant->checkin_token,
                'checked_in' => false,
            ]);
    }

    public function test_lookup_marks_users_registered_today()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create([
            'first_name' => 'Luis',
            'last_name' => 'Ramírez',
        ]);
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])->assertOk();

        $this->get('/checkin/lookup?search=ram')
            ->assertOk()
            ->assertJsonFragment(['id' => $participant->id, 'checked_in' => true]);
    }

    public function test_checkin_rejects_duplicate_registration()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])->assertOk();
        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertOk()
            ->assertJson(['already' => true]);
    }

    public function test_checkin_is_disabled_when_setting_off()
    {
        Setting::create(['key' => 'evento_checkin_enabled', 'value' => '0']);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertStatus(422);
    }

    public function test_checkin_is_per_day_and_certificate_requires_min_days()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        Setting::updateOrCreate(['key' => 'evento_min_dias'], ['value' => '2']);
        Setting::updateOrCreate(['key' => 'evento_fecha_inicio'], ['value' => now()->format('Y-m-d')]);
        Setting::updateOrCreate(['key' => 'evento_fecha_fin'], ['value' => now()->addDay()->format('Y-m-d')]);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->travelTo(now()->startOfDay());

        $first = $this->postJson('/checkin/register', ['token' => $participant->checkin_token]);
        $first->assertOk()
            ->assertJson(['success' => true, 'qualifies' => false, 'certificate_issued' => false]);
        $this->assertDatabaseMissing('certificates', ['user_id' => $participant->id, 'event_type' => 'event']);

        $this->travelTo(now()->startOfDay()->addDay());

        $second = $this->postJson('/checkin/register', ['token' => $participant->checkin_token]);
        $second->assertOk()
            ->assertJson(['success' => true, 'qualifies' => true, 'certificate_issued' => true]);

        $this->assertSame(2, Attendance::query()
            ->where('user_id', $participant->id)
            ->whereNull('workshop_id')
            ->whereNull('presentation_id')
            ->distinct()
            ->count('event_day'));

        $this->travelBack();
    }

    public function test_checkin_rejects_same_day_duplicate_but_allows_next_day()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        Setting::updateOrCreate(['key' => 'evento_fecha_inicio'], ['value' => now()->format('Y-m-d')]);
        Setting::updateOrCreate(['key' => 'evento_fecha_fin'], ['value' => now()->addDay()->format('Y-m-d')]);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->travelTo(now()->startOfDay());
        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])->assertOk();

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertOk()
            ->assertJson(['already' => true]);

        $this->travelTo(now()->startOfDay()->addDay());

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertOk()
            ->assertJson(['success' => true]);

        $this->travelBack();
    }

    public function test_checkin_rejects_outside_event_dates()
    {
        $this->enableEventCheckin();
        Setting::updateOrCreate(['key' => 'evento_fecha_inicio'], ['value' => now()->subDay()->format('Y-m-d')]);
        Setting::updateOrCreate(['key' => 'evento_fecha_fin'], ['value' => now()->format('Y-m-d')]);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->travelTo(now()->addDay()->startOfDay());

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertStatus(422)
            ->assertJson(['success' => false]);

        $this->travelBack();
    }

    public function test_checkin_allows_outside_event_dates_when_time_restriction_disabled()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        Setting::updateOrCreate(['key' => 'evento_checkin_time_restricted'], ['value' => '0']);
        Setting::updateOrCreate(['key' => 'evento_fecha_inicio'], ['value' => now()->subDay()->format('Y-m-d')]);
        Setting::updateOrCreate(['key' => 'evento_fecha_fin'], ['value' => now()->format('Y-m-d')]);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->travelTo(now()->addDay()->startOfDay());

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertOk()
            ->assertJson(['success' => true]);

        $this->travelBack();
    }

    public function test_event_constancia_is_blocked_until_min_days_met()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        Setting::updateOrCreate(['key' => 'evento_min_dias'], ['value' => '2']);
        Setting::updateOrCreate(['key' => 'evento_fecha_inicio'], ['value' => now()->format('Y-m-d')]);
        Setting::updateOrCreate(['key' => 'evento_fecha_fin'], ['value' => now()->addDay()->format('Y-m-d')]);
        $user = $this->userWith('Asistente', ['gafete.view', 'constancias.view', 'constancias.download']);
        $admin = $this->admin();

        $this->travelTo(now()->startOfDay());
        Attendance::create([
            'user_id' => $user->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($user);

        $this->get('/constancias/evento/download')
            ->assertRedirect()
            ->assertSessionHasErrors('error');

        $this->travelTo(now()->startOfDay()->addDay());
        Attendance::create([
            'user_id' => $user->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);

        $response = $this->get('/constancias/evento/download');
        $response->assertOk();
        $this->assertStringContainsString($user->first_name, $response->getContent());

        $this->travelBack();
    }

    public function test_generate_constancias_skips_users_below_min_days()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        Setting::updateOrCreate(['key' => 'evento_min_dias'], ['value' => '2']);
        $admin = $this->admin();
        $partial = User::factory()->create();
        $complete = User::factory()->create();
        Attendance::create([
            'user_id' => $partial->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        Attendance::create([
            'user_id' => $complete->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        Attendance::create([
            'user_id' => $complete->id,
            'event_day' => now()->subDay()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $this->post('/admin/evento/generar-constancias')->assertRedirect();

        $this->assertDatabaseHas('certificates', ['user_id' => $complete->id, 'event_type' => 'event']);
        $this->assertDatabaseMissing('certificates', ['user_id' => $partial->id, 'event_type' => 'event']);
    }

    public function test_admin_can_delete_event_attendance()
    {
        $admin = $this->admin();
        $participant = User::factory()->create();
        $attendance = Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $this->delete('/admin/evento/attendance/'.$attendance->id)
            ->assertRedirect();

        $this->assertDatabaseMissing('attendances', ['id' => $attendance->id]);
    }

    public function test_non_admin_cannot_delete_event_attendance()
    {
        $admin = $this->admin();
        $participant = User::factory()->create();
        $attendance = Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->delete('/admin/evento/attendance/'.$attendance->id)
            ->assertForbidden();

        $this->assertDatabaseHas('attendances', ['id' => $attendance->id]);
    }

    public function test_evento_index_filters_attendances_by_day()
    {
        $this->enableEventCheckin();
        $admin = $this->admin();
        $today = now()->format('Y-m-d');
        $tomorrow = now()->addDay()->format('Y-m-d');
        $userToday = User::factory()->create();
        $userTomorrow = User::factory()->create();
        Attendance::create(['user_id' => $userToday->id, 'event_day' => $today, 'registered_by' => $admin->id]);
        Attendance::create(['user_id' => $userTomorrow->id, 'event_day' => $tomorrow, 'registered_by' => $admin->id]);
        $this->actingAs($admin);

        $this->get('/admin/evento?day='.$today)
            ->assertOk()
            ->assertInertia(fn ($page) => $page
                ->component('Evento/Index')
                ->where('selected_day', $today)
                ->has('attendances', 1));

        $this->get('/admin/evento')
            ->assertOk()
            ->assertInertia(fn ($page) => $page
                ->component('Evento/Index')
                ->where('selected_day', null)
                ->has('attendances', 2));
    }

    public function test_admin_can_access_and_update_evento_settings()
    {
        $this->enableEventCheckin();
        $this->actingAs($this->admin());

        $this->get('/admin/evento')->assertOk();

        $this->put('/admin/evento', [
            'evento_nombre' => 'EICAL 2027',
            'evento_checkin_enabled' => 0,
            'evento_checkin_grace_hours' => 3,
            'evento_min_dias' => 4,
            'evento_fecha_inicio' => '2027-03-01',
            'evento_fecha_fin' => '2027-03-04',
        ])->assertRedirect();

        $this->assertDatabaseHas('settings', ['key' => 'evento_nombre', 'value' => 'EICAL 2027']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_checkin_enabled', 'value' => '0']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_checkin_grace_hours', 'value' => '3']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_min_dias', 'value' => '4']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_fecha_inicio', 'value' => '2027-03-01']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_fecha_fin', 'value' => '2027-03-04']);
    }

    public function test_evento_settings_reject_min_days_greater_than_total_days()
    {
        $this->enableEventCheckin();
        $this->actingAs($this->admin());

        $response = $this->put('/admin/evento', [
            'evento_nombre' => 'EICAL 2028',
            'evento_checkin_enabled' => 1,
            'evento_checkin_grace_hours' => 2,
            'evento_min_dias' => 5,
            'evento_fecha_inicio' => '2028-03-01',
            'evento_fecha_fin' => '2028-03-04',
        ]);

        $response->assertSessionHasErrors('evento_min_dias');
        $this->assertDatabaseMissing('settings', ['key' => 'evento_min_dias', 'value' => '5']);
    }

    public function test_evento_settings_accept_min_days_equal_to_total_days()
    {
        $this->enableEventCheckin();
        $this->actingAs($this->admin());

        $this->put('/admin/evento', [
            'evento_nombre' => 'EICAL 2028',
            'evento_checkin_enabled' => 1,
            'evento_checkin_grace_hours' => 2,
            'evento_min_dias' => 4,
            'evento_fecha_inicio' => '2028-03-01',
            'evento_fecha_fin' => '2028-03-04',
        ])->assertRedirect();

        $this->assertDatabaseHas('settings', ['key' => 'evento_min_dias', 'value' => '4']);
    }

    public function test_evento_settings_reject_grace_hours_out_of_range()
    {
        $this->enableEventCheckin();
        $this->actingAs($this->admin());

        $response = $this->put('/admin/evento', [
            'evento_nombre' => 'EICAL 2028',
            'evento_checkin_enabled' => 1,
            'evento_checkin_grace_hours' => 25,
            'evento_min_dias' => 4,
            'evento_fecha_inicio' => '2028-03-01',
            'evento_fecha_fin' => '2028-03-04',
        ]);

        $response->assertSessionHasErrors('evento_checkin_grace_hours');
        $this->assertDatabaseMissing('settings', ['key' => 'evento_checkin_grace_hours', 'value' => '25']);
    }

    public function test_non_admin_cannot_manage_evento()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/admin/evento')->assertForbidden();
    }

    public function test_generate_constancias_issues_event_certificates()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $admin = $this->admin();
        $participant = User::factory()->create();
        Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $this->post('/admin/evento/generar-constancias')->assertRedirect();

        $this->assertDatabaseHas('certificates', [
            'user_id' => $participant->id,
            'event_type' => 'event',
        ]);
    }

    public function test_user_can_download_event_constancia_after_checkin()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $user = $this->userWith('Asistente', ['gafete.view', 'constancias.view', 'constancias.download']);
        Attendance::create([
            'user_id' => $user->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $user->id,
        ]);
        $this->actingAs($user);

        $response = $this->get('/constancias/evento/download');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
        $this->assertStringContainsString($user->first_name, $response->getContent());
        $this->assertStringContainsString('Asistente al evento', $response->getContent());
    }

    public function test_admin_can_download_any_user_event_constancia()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $admin = $this->admin();
        $participant = User::factory()->create();
        Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $response = $this->get('/admin/constancias/evento/'.$participant->id.'/download');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
    }

    public function test_admin_can_manage_badge_templates()
    {
        $this->actingAs($this->admin());

        $this->get('/admin/gafetes/plantillas')->assertOk();

        $this->post('/admin/gafetes/plantillas', [
            'name' => 'Gafete de prueba',
            'is_default' => true,
        ])->assertRedirect();

        $template = CertificateTemplate::where('kind', 'badge')->where('name', 'Gafete de prueba')->first();
        $this->assertNotNull($template);

        $this->get('/admin/gafetes/plantillas/'.$template->id.'/edit')->assertOk();

        $this->put('/admin/gafetes/plantillas/'.$template->id, [
            'name' => 'Gafete actualizado',
            'is_default' => true,
            'elements' => [
                [
                    'type' => 'image',
                    'x' => 100,
                    'y' => 100,
                    'width' => 200,
                    'height' => 200,
                    'z_index' => 1,
                ],
                [
                    'type' => 'text',
                    'content' => '{nombre}',
                    'x' => 100,
                    'y' => 400,
                    'width' => 800,
                    'height' => 60,
                    'font_size' => 30,
                    'text_align' => 'center',
                    'z_index' => 2,
                ],
            ],
        ])->assertRedirect();

        $this->assertDatabaseHas('certificate_template_elements', [
            'template_id' => $template->id,
            'type' => 'image',
        ]);

        $this->delete('/admin/gafetes/plantillas/'.$template->id)->assertRedirect();
        $this->assertSoftDeleted('certificate_templates', ['id' => $template->id]);
    }

    public function test_badge_template_rejects_image_element_on_certificate_kind()
    {
        $admin = $this->admin();
        $this->actingAs($admin);
        $type = ParticipationType::create([
            'key' => 'taller',
            'label' => 'Taller',
            'event_kind' => 'workshop',
            'role' => 'enrolled_attendance',
            'is_active' => true,
        ]);

        $response = $this->post('/admin/constancias/plantillas', [
            'name' => 'Plantilla inválida',
            'participation_type_id' => $type->id,
            'elements' => [
                ['type' => 'image', 'x' => 0, 'y' => 0],
            ],
        ]);

        $response->assertSessionHasErrors('elements.0.type');
    }

    public function test_non_admin_cannot_manage_badge_templates()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/admin/gafetes/plantillas')->assertForbidden();
    }

    public function test_issue_event_uses_event_participation_type()
    {
        $this->eventoType();
        $user = User::factory()->create();

        $certificate = app(CertificateRenderer::class)->issueEvent($user);

        $this->assertNotNull($certificate);
        $this->assertSame('event', $certificate->event_type);
        $this->assertNotNull($certificate->folio);
        $this->assertStringStartsWith('EICAL-', $certificate->folio);
    }

    public function test_staff_can_send_attendance_qr_to_instructor()
    {
        $user = $this->userWith('Administrator', ['workshops.attendance', 'workshops.qr.send']);
        $this->actingAs($user);

        $workshop = Workshop::create([
            'name' => 'Taller QR',
            'description' => 'test',
            'capacity' => 10,
            'location' => 'Aula 1',
            'day' => now()->format('Y-m-d'),
            'start_time' => '09:00',
            'end_time' => '11:00',
            'qr_time_restricted' => false,
            'created_by' => $user->id,
        ]);

        $instructor = User::factory()->create(['email' => 'instructor@test.com']);
        $workshop->instructors()->attach($instructor->id);

        $this->post("/admin/workshops/{$workshop->id}/send-qr", ['user_id' => $instructor->id])
            ->assertRedirect();

        $this->assertDatabaseHas('event_logs', [
            'event_key' => 'workshop.qr_sent',
            'subject_type' => 'workshop',
            'subject_id' => $workshop->id,
            'status' => 'recorded',
        ]);
    }

    public function test_csv_import_creates_users_with_activation_link()
    {
        $this->actingAs($this->admin());

        $csv = "nombre,apellido,email,rol\nMaria,Garcia,maria@correo.mx,Asistente\n";
        $file = UploadedFile::fake()->createWithContent('users.csv', $csv);

        $this->post(route('users.import'), ['csv_file' => $file])
            ->assertSessionHas('success');

        $user = User::where('email', 'maria@correo.mx')->first();
        $this->assertNotNull($user);
        $this->assertNotNull($user->activation_token);
        $this->assertDatabaseHas('event_logs', ['event_key' => 'user.welcome', 'subject_id' => $user->id]);
    }

    public function test_csv_import_reactivates_existing_users_without_password()
    {
        $this->actingAs($this->admin());

        $existing = User::factory()->create([
            'email' => 'maria@correo.mx',
            'password_set_at' => null,
            'activation_token' => null,
        ]);

        $csv = "nombre,apellido,email,rol\nMaria,Garcia,maria@correo.mx,Asistente\n";
        $file = UploadedFile::fake()->createWithContent('users.csv', $csv);

        $this->post(route('users.import'), ['csv_file' => $file])
            ->assertSessionHas('success');

        $existing->refresh();
        $this->assertNotNull($existing->activation_token);
        $this->assertDatabaseHas('event_logs', ['event_key' => 'user.welcome', 'subject_id' => $existing->id]);
    }

    public function test_csv_import_preserves_existing_user_account_and_gains_role()
    {
        $this->actingAs($this->admin());

        $asistenteRole = Role::firstOrCreate(['name' => 'Asistente']);
        $ponenteRole = Role::firstOrCreate(['name' => 'Ponente']);

        $asistente = User::factory()->create([
            'email' => 'carla@correo.mx',
            'password_set_at' => now(),
            'activation_token' => null,
        ]);
        $asistente->roles()->sync([$asistenteRole->id]);
        $password = $asistente->password;
        $dni = $asistente->dni;

        $csv = "nombre,apellido,email,,,,rol\nCarla,Lopez,carla@correo.mx,,,,Ponente\n";
        $file = UploadedFile::fake()->createWithContent('users.csv', $csv);

        $this->post(route('users.import'), ['csv_file' => $file])
            ->assertSessionHas('success');

        $asistente->refresh();
        $this->assertSame($password, $asistente->password);
        $this->assertSame($dni, $asistente->dni);
        $this->assertTrue($asistente->roles()->where('roles.id', $asistenteRole->id)->exists());
        $this->assertTrue($asistente->roles()->where('roles.id', $ponenteRole->id)->exists());
        $this->assertDatabaseMissing('event_logs', ['event_key' => 'user.welcome', 'subject_id' => $asistente->id]);
    }
}
