<?php

namespace Tests\Feature;

use App\Models\Attendance;
use App\Models\CertificateTemplate;
use App\Models\ParticipationType;
use App\Models\Permission;
use App\Models\Role;
use App\Models\Setting;
use App\Models\User;
use App\Services\CertificateRenderer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class RegistroModuleTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        $user = User::factory()->create();
        $role = Role::firstOrCreate(['name' => 'Administrator']);
        $user->roles()->sync([$role->id]);

        return $user;
    }

    private function userWith(string $roleName, array $permissionKeys): User
    {
        $role = Role::firstOrCreate(['name' => $roleName]);

        foreach ($permissionKeys as $key) {
            $role->permissions()->syncWithoutDetaching(
                Permission::create([
                    'key' => $key,
                    'module' => 'Test',
                    'label' => $key,
                ])
            );
        }

        $user = User::factory()->create();
        $user->roles()->sync([$role->id]);

        return $user;
    }

    private function eventoType(): ParticipationType
    {
        return ParticipationType::create([
            'key' => 'evento_asistencia',
            'label' => 'Asistente al evento',
            'event_kind' => 'event',
            'role' => null,
            'is_active' => true,
        ]);
    }

    private function enableEventCheckin(): void
    {
        Setting::create(['key' => 'evento_checkin_enabled', 'value' => '1']);
        Setting::create(['key' => 'evento_nombre', 'value' => 'EICAL 2026']);
    }

    private function badgeTemplate(): CertificateTemplate
    {
        $template = CertificateTemplate::create([
            'name' => 'Gafete base',
            'kind' => 'badge',
            'is_default' => true,
            'width' => 1000,
            'height' => 1500,
        ]);

        $template->elements()->create([
            'type' => 'text',
            'content' => '{nombre}',
            'x' => 100,
            'y' => 100,
            'width' => 800,
            'height' => 60,
            'font_size' => 40,
            'font_weight' => 'bold',
            'text_align' => 'center',
            'z_index' => 1,
        ]);

        return $template;
    }

    public function test_checkin_token_is_autogenerated_when_user_is_created()
    {
        $user = User::factory()->create();

        $this->assertNotNull($user->checkin_token);
        $this->assertStringStartsWith('GFT-', $user->checkin_token);
    }

    public function test_user_can_view_own_gafete()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/gafete')->assertOk();
    }

    public function test_user_without_permission_cannot_view_gafete()
    {
        $user = $this->userWith('Asistente', ['dashboard.view']);
        $this->actingAs($user);

        $this->get('/gafete')->assertForbidden();
    }

    public function test_user_can_print_badge_html()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $response = $this->get('/gafete/imprimir');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
        $this->assertStringContainsString($user->first_name, $response->getContent());
        $this->assertStringContainsString('EICAL 2026', $response->getContent());
        $this->assertStringContainsString('data:image/svg+xml;base64', $response->getContent());
    }

    public function test_user_can_download_badge_pdf()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $response = $this->get('/gafete/imprimir/pdf');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'application/pdf');
        $this->assertStringStartsWith('%PDF', $response->getContent());
    }

    public function test_badge_template_is_used_when_available()
    {
        $this->badgeTemplate();
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $content = $this->get('/gafete/imprimir')->getContent();

        $this->assertStringContainsString($user->first_name, $content);
        $this->assertStringNotContainsString('badge-name', $content);
    }

    public function test_scan_info_page_is_public()
    {
        $this->get('/gafete/escaneo?token=GFT-ABC')
            ->assertOk()
            ->assertSee('GFT-ABC');
    }

    public function test_staff_with_permission_can_access_checkin()
    {
        $this->enableEventCheckin();
        $user = $this->userWith('Ponente', ['checkin.scan']);
        $this->actingAs($user);

        $this->get('/checkin')->assertOk();
    }

    public function test_user_without_permission_cannot_access_checkin()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/checkin')->assertForbidden();
    }

    public function test_checkin_registers_attendance_and_issues_event_certificate()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $response = $this->postJson('/checkin/register', ['token' => $participant->checkin_token]);

        $response->assertOk()->assertJson(['success' => true]);
        $this->assertDatabaseHas('attendances', [
            'user_id' => $participant->id,
            'workshop_id' => null,
            'presentation_id' => null,
        ]);
        $this->assertDatabaseHas('certificates', [
            'user_id' => $participant->id,
            'event_type' => 'event',
        ]);
    }

    public function test_checkin_rejects_invalid_token()
    {
        $this->enableEventCheckin();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => 'GFT-INVALIDO'])
            ->assertNotFound();
    }

    public function test_checkin_rejects_duplicate_registration()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])->assertOk();
        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertOk()
            ->assertJson(['already' => true]);
    }

    public function test_checkin_is_disabled_when_setting_off()
    {
        Setting::create(['key' => 'evento_checkin_enabled', 'value' => '0']);
        $staff = $this->userWith('Ponente', ['checkin.scan']);
        $participant = User::factory()->create();
        $this->actingAs($staff);

        $this->postJson('/checkin/register', ['token' => $participant->checkin_token])
            ->assertStatus(422);
    }

    public function test_admin_can_access_and_update_evento_settings()
    {
        $this->enableEventCheckin();
        $this->actingAs($this->admin());

        $this->get('/admin/evento')->assertOk();

        $this->put('/admin/evento', [
            'evento_nombre' => 'EICAL 2027',
            'evento_checkin_enabled' => 0,
            'evento_min_dias' => 5,
        ])->assertRedirect();

        $this->assertDatabaseHas('settings', ['key' => 'evento_nombre', 'value' => 'EICAL 2027']);
        $this->assertDatabaseHas('settings', ['key' => 'evento_checkin_enabled', 'value' => '0']);
    }

    public function test_non_admin_cannot_manage_evento()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/admin/evento')->assertForbidden();
    }

    public function test_generate_constancias_issues_event_certificates()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $admin = $this->admin();
        $participant = User::factory()->create();
        Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $this->post('/admin/evento/generar-constancias')->assertRedirect();

        $this->assertDatabaseHas('certificates', [
            'user_id' => $participant->id,
            'event_type' => 'event',
        ]);
    }

    public function test_user_can_download_event_constancia_after_checkin()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $user = $this->userWith('Asistente', ['gafete.view', 'constancias.view', 'constancias.download']);
        Attendance::create([
            'user_id' => $user->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $user->id,
        ]);
        $this->actingAs($user);

        $response = $this->get('/constancias/evento/download');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
        $this->assertStringContainsString($user->first_name, $response->getContent());
        $this->assertStringContainsString('Asistente al evento', $response->getContent());
    }

    public function test_admin_can_download_any_user_event_constancia()
    {
        $this->enableEventCheckin();
        $this->eventoType();
        $admin = $this->admin();
        $participant = User::factory()->create();
        Attendance::create([
            'user_id' => $participant->id,
            'event_day' => now()->format('Y-m-d'),
            'registered_by' => $admin->id,
        ]);
        $this->actingAs($admin);

        $response = $this->get('/admin/constancias/evento/'.$participant->id.'/download');

        $response->assertOk();
        $response->assertHeader('Content-Type', 'text/html; charset=utf-8');
    }

    public function test_admin_can_manage_badge_templates()
    {
        $this->actingAs($this->admin());

        $this->get('/admin/gafetes/plantillas')->assertOk();

        $this->post('/admin/gafetes/plantillas', [
            'name' => 'Gafete de prueba',
            'is_default' => true,
        ])->assertRedirect();

        $template = CertificateTemplate::where('kind', 'badge')->where('name', 'Gafete de prueba')->first();
        $this->assertNotNull($template);

        $this->get('/admin/gafetes/plantillas/'.$template->id.'/edit')->assertOk();

        $this->put('/admin/gafetes/plantillas/'.$template->id, [
            'name' => 'Gafete actualizado',
            'is_default' => true,
            'elements' => [
                [
                    'type' => 'image',
                    'x' => 100,
                    'y' => 100,
                    'width' => 200,
                    'height' => 200,
                    'z_index' => 1,
                ],
                [
                    'type' => 'text',
                    'content' => '{nombre}',
                    'x' => 100,
                    'y' => 400,
                    'width' => 800,
                    'height' => 60,
                    'font_size' => 30,
                    'text_align' => 'center',
                    'z_index' => 2,
                ],
            ],
        ])->assertRedirect();

        $this->assertDatabaseHas('certificate_template_elements', [
            'template_id' => $template->id,
            'type' => 'image',
        ]);

        $this->delete('/admin/gafetes/plantillas/'.$template->id)->assertRedirect();
        $this->assertSoftDeleted('certificate_templates', ['id' => $template->id]);
    }

    public function test_badge_template_rejects_image_element_on_certificate_kind()
    {
        $admin = $this->admin();
        $this->actingAs($admin);
        $type = ParticipationType::create([
            'key' => 'taller',
            'label' => 'Taller',
            'event_kind' => 'workshop',
            'role' => 'enrolled_attendance',
            'is_active' => true,
        ]);

        $response = $this->post('/admin/constancias/plantillas', [
            'name' => 'Plantilla inválida',
            'participation_type_id' => $type->id,
            'elements' => [
                ['type' => 'image', 'x' => 0, 'y' => 0],
            ],
        ]);

        $response->assertSessionHasErrors('elements.0.type');
    }

    public function test_non_admin_cannot_manage_badge_templates()
    {
        $user = $this->userWith('Asistente', ['gafete.view']);
        $this->actingAs($user);

        $this->get('/admin/gafetes/plantillas')->assertForbidden();
    }

    public function test_issue_event_uses_event_participation_type()
    {
        $this->eventoType();
        $user = User::factory()->create();

        $certificate = app(CertificateRenderer::class)->issueEvent($user);

        $this->assertNotNull($certificate);
        $this->assertSame('event', $certificate->event_type);
        $this->assertNotNull($certificate->folio);
        $this->assertStringStartsWith('EICAL-', $certificate->folio);
    }
}
